version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: mpl-ville-server
    restart: unless-stopped
    ports:
      - "4080:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
      - JWT_ENCRYPTION_KEY=changeme
    networks:
      - mpl-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:4000/api/results"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mpl-ville-frontend
    restart: unless-stopped
    ports:
      - "4081:80"
    depends_on:
      - server
    networks:
      - mpl-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  mpl-network:
    driver: bridge
